version: '3'

services:
  watson-postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5430:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  postgres-volume:
